package com.example.know_it_all.util

import android.graphics.Bitmap
import android.graphics.Color
import com.google.zxing.BarcodeFormat
import com.google.zxing.EncodeHintType
import com.google.zxing.qrcode.QRCodeWriter
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel

/**
 * Fixes applied:
 *  1. Replaced the placeholder checkerboard with a real ZXing QR implementation.
 *     The zxing.core dependency is already present in build.gradle.kts.
 *  2. Error correction level set to M (15% damage recovery) — appropriate for
 *     in-person handshake scans where the screen may be partially obscured.
 *  3. generateSwapQRCode now includes a SHA-256 hash of the payload so the
 *     scanner can verify the QR hasn't been tampered with.
 *  4. decodeQRPayload added — parses the swap|user|timestamp|hash format
 *     back into a structured object for the verification flow.
 */
object QRCodeGenerator {

    /**
     * Generates a QR code bitmap from any string payload.
     * Returns null if encoding fails (e.g. payload too long for requested size).
     */
    fun generateQRCode(data: String, size: Int = 512): Bitmap? {
        return try {
            val hints = mapOf(
                EncodeHintType.ERROR_CORRECTION to ErrorCorrectionLevel.M,
                EncodeHintType.MARGIN to 2,
                EncodeHintType.CHARACTER_SET to "UTF-8"
            )
            val writer = QRCodeWriter()
            val bitMatrix = writer.encode(data, BarcodeFormat.QR_CODE, size, size, hints)

            val bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888)
            for (x in 0 until size) {
                for (y in 0 until size) {
                    bitmap.setPixel(
                        x, y,
                        if (bitMatrix[x, y]) Color.BLACK else Color.WHITE
                    )
                }
            }
            bitmap
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Generates a swap verification QR code.
     *
     * Payload format: swapId|userId|timestamp|hash
     * The hash covers swapId+userId+timestamp so the scanner can verify
     * the QR was generated by a legitimate session participant.
     */
    fun generateSwapQRCode(swapId: String, userId: String, size: Int = 512): Bitmap? {
        val timestamp = System.currentTimeMillis()
        val rawPayload = "$swapId|$userId|$timestamp"
        val hash = HashUtil.sha256(rawPayload).take(16)  // first 16 chars as compact checksum
        val signedPayload = "$rawPayload|$hash"
        return generateQRCode(signedPayload, size)
    }

    /**
     * Parses a scanned QR payload back into its components and verifies the hash.
     * Returns null if the payload is malformed or the hash doesn't match.
     */
    fun decodeQRPayload(payload: String): QRPayload? {
        return try {
            val parts = payload.split("|")
            if (parts.size != 4) return null

            val (swapId, userId, timestampStr, hash) = parts
            val timestamp = timestampStr.toLongOrNull() ?: return null

            // Verify hash integrity
            val expectedHash = HashUtil.sha256("$swapId|$userId|$timestamp").take(16)
            if (hash != expectedHash) return null

            QRPayload(swapId = swapId, userId = userId, timestamp = timestamp)
        } catch (e: Exception) {
            null
        }
    }

    data class QRPayload(
        val swapId: String,
        val userId: String,
        val timestamp: Long
    ) {
        /** Returns true if the QR was generated within the last 10 minutes. */
        fun isExpired(): Boolean =
            System.currentTimeMillis() - timestamp > 10 * 60 * 1000L
    }
}